os: linux
dist: xenial
language: generic
services:
  - docker
env:
  global:
    - DOCKER="goldarte/img-tool:v0.5"
    - TARGET_REPO="https://github.com/${TRAVIS_REPO_SLUG}.git"
    - IMAGE_VERSION=${TRAVIS_TAG:-${TRAVIS_COMMIT:0:7}}
    - IMAGE_NAME="$(basename -s '.git' ${TARGET_REPO})_${IMAGE_VERSION}.img"
git:
  depth: 25
jobs:
  fast_finish: true
  include:
    - stage: Build
      name: "Raspberry Pi Image Build"
      cache:
        directories:
        - imgcache
      before_script:
        - docker pull ${DOCKER}
        # Check if there are any cached images, copy them to our "images" directory
        - if [ -n "$(ls -A imgcache/*.zip)" ]; then mkdir -p images && cp imgcache/*.zip images; fi
      script:
        - docker run --privileged --rm -v /dev:/dev -v $(pwd):/mnt -e TRAVIS_TAG="${TRAVIS_TAG}" ${DOCKER}
      before_cache:
        - cp images/*.zip imgcache
      after_success:
        - sudo chmod -R 777 *
        - cd images && zip -9 ${IMAGE_NAME}.zip ${IMAGE_NAME} && stat --printf="Compressed image size:%s\n" ${IMAGE_NAME}.zip
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "vas0x59"
        - git config --local user.email "vasily.yuryev.a1@gmail.com"
        # - sudo chmod -R 777 *
        # - cd images && zip ${IMAGE_NAME}.zip ${IMAGE_NAME}
      deploy:
        provider: releases
        token: ${GITHUB_OAUTH_TOKEN}
        file: ${IMAGE_NAME}.zip
        skip_cleanup: true
        on:
          tags: true
        draft: true
        name: ${TRAVIS_TAG}
stages:
  - Build